### ISSUE TITLE
gallery_get fails 'decode' error.

### ISSUE THREAD

**Issue by hrothgar2011** [regosen/gallery_get#15]
---

Traceback (most recent call last):
  File "gallery_get.py", line 273, in run
    self.run_internal()
  File "gallery_get.py", line 251, in run_internal
    jpegs = run_match(PLUGIN.direct,response.read().decode('utf-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 44940: invalid start byte

**Comment by hrothgar2011** [comment]
I've seen this type of error for several versions of python, 2.7.5 and 3.5.2. But in different places for different files.

**Comment by regosen** [comment]
This should've been fixed in December with pull requests from talha252
