### ISSUE TITLE
pornhub plugin error : TypeError: 'map' object is not subscriptable

### ISSUE THREAD

**Issue by HiTechRabbit** [regosen/gallery_get#39]
Hello there,

I tried to download content from a specific redditor but it seems that pornhub plugin does have problems.

```
Using pornhub_video plugin...

------------------------------------------------------------
Traceback (most recent call last):
  File "/path/user/venv/lib64/python3.6/site-packages/gallery_get.py", line 450, in run_wrapped
    root = GalleryGet(myurl, dest or DEST_ROOT, titleAsFolder, allowGenericPlugin).run()
  File "/path/user/venv/lib64/python3.6/site-packages/gallery_get.py", line 441, in run
    return self.queue_jobs(page, plugin, root, subtitle)
  File "/path/user/venv/lib64/python3.6/site-packages/gallery_get.py", line 387, in queue_jobs
    links = run_match(plugin.direct, page)
  File "/path/user/venv/lib64/python3.6/site-packages/gallery_get.py", line 102, in run_match
    result = match(source)
  File "/path/user/venv/lib64/python3.6/site-packages/gallery_plugins/plugin_pornhub_video.py", line 24, in direct_links
    return map(lambda x: x.replace("\/", "/"), links)[0] # highest-quality video is listed first
TypeError: 'map' object is not subscriptable
Using params: ['https://www.pornhub.com/view_video.php?viewkey=ph5ad7a56173a4d', '/path/user/downloads/fulloffantasies/2018-04-19 - A compilation vid of me having fun with my med_soft Rex! [F]', True]
------------------------------------------------------------

```

**Comment by regosen** [comment]
Thanks for submitting the issue!  Should be fixed now.
