### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by Kvasmuppet** [regosen/gallery_get#45]
Lines asked to copy:

------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\Lib\site-packages\gallery_get.py", line 323, in run
    self.run_internal()
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\Lib\site-packages\gallery_get.py", line 313, in run_internal
    while not self.copy_image(info):
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\Lib\site-packages\gallery_get.py", line 252, in copy_image
    if not info.write_to_file(file_info, file_name):
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\Lib\site-packages\gallery_get.py", line 177, in write_to_file
    output = open(file_name,'wb')
OSError: [Errno 22] Invalid argument: 'E:\\Reddit\\SashaCharm\\2018-07-30 - [F]irst time here!.jpg?1.jpg'
Using params: ['reddit_get.py', 'SashaCharm', 'E:\\Reddit\\']
------------------------------------------------------------

I can see the problem, the ? mark is an illegal and reserved character in windows. I am not sure why this happens though. It happens on multiple various links.

**Comment by regosen** [comment]
Thanks for catching this and providing an example.  I just submitted a fix for it now, hopefully it will work for you!

**Comment by Kvasmuppet** [comment]
It seems to be working with the fix you provided.
