### ISSUE TITLE
pornhub album

### ISSUE THREAD

**Issue by Gelien** [regosen/gallery_get#52]
Traceback (most recent call last):
  File "gallery_get.py", line 450, in run_wrapped
    root = GalleryGet(myurl, dest or DEST_ROOT, titleAsFolder, allowGenericPlugin).run()
  File "gallery_get.py", line 441, in run
    return self.queue_jobs(page, plugin, root, subtitle)
  File "gallery_get.py", line 377, in queue_jobs
    links = run_match(plugin.redirect, page)
  File "gallery_get.py", line 102, in run_match
    result = match(source)
  File "C:\Users\callm\Desktop\steam pics\gallery_get-1.8.0\gallery_get-1.8.0\gallery_plugins\plugin_pornhub_album.py", line 20, in redirect
    cur_url = re.findall(r'link rel="canonical" href="(.+?)"', source)[0].split("?")[0]
IndexError: list index out of range
Using params: ['https://www.pornhub.com/album/24624802', 'C:\\Users\\callm\\Desktop\\steam pics\\gallery_get-1.8.0\\gallery_get-1.8.0', False]

on lastest updated, worked once then stopped. tried deleting and re downloading

**Comment by regosen** [comment]
Please try again with my update (gallery_get version 1.8.1).  I couldn't reproduce the error with the URL you used, but I just submitted a fix to not throw an exception when the conditions are met.

**Comment by regosen** [comment]
Interesting, I was able to this intermittently, turns out the URL request can return a minimal "Loading ..." page if it doesn't have enough time to load.  I've added a fix (1.8.2), it will take much longer to start downloading images, but it's the only way to be sure.

Please let me know if you still encounter errors.

**Comment by Gelien** [comment]
PS C:\Users\callm\Desktop\steam pics\gallery_get-1.8.2> python gallery_get.py
Input URL: https://www.pornhub.com/album/24624802
Destination (C:\Users\callm\Desktop\steam pics\gallery_get-1.8.2):
Using pornhub_album plugin...
No links found at https://www.pornhub.com/album/24624802, please check URL and try again.
Sites occasionally change their markup.  Check if this tool has an update.
 - https://github.com/regosen/gallery_get
 - pip install gallery_get --update
Errors were encountered!  Please check messages above.

same error

**Comment by regosen** [comment]
That's odd, I even backed out the change that affected 1.8.0.  When you say it worked for you in the past with no issue, were you using it on pornhub albums in the past?

**Comment by Gelien** [comment]
i was using version 1.6.1 for a while before pornhub updated. with 1.8.1 it worked once then when i tried another one it stopped working

**Comment by Gelien** [comment]
i managed to get it to work sometimes with a VM but sometimes it will skip some of the images saying "No links found at redirected page: https://www.pornhub.com/photo/84642651"
