### ISSUE TITLE
Error: Using fuskator plugin...

### ISSUE THREAD

**Issue by twodragonsrob** [regosen/gallery_get#60]
As recommended :-)

Using fuskator plugin...
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gallery_get.py", line 449, in run_wrapped
    root = GalleryGet(myurl, dest or DEST_ROOT, titleAsFolder, allowGenericPlugin).run()
  File "/usr/local/lib/python3.7/dist-packages/gallery_get.py", line 440, in run
    return self.queue_jobs(page, root, subtitle)
  File "/usr/local/lib/python3.7/dist-packages/gallery_get.py", line 375, in queue_jobs
    links = run_match(self.plugin.redirect, page)
  File "/usr/local/lib/python3.7/dist-packages/gallery_get.py", line 111, in run_match
    result = match(source)
  File "/usr/local/lib/python3.7/dist-packages/gallery_plugins/plugin_fuskator.py", line 21, in redirect
    root = matcher.findall(source)[0].replace('%2f', '/')
IndexError: list index out of range
Using params: ['https://fuskator.com/thumbs/kPh5EdVVHcP/Nude-Naked-Celeb-Katie-Price-with-Nice-Pussy.html', '', False]
------------------------------------------------------------

**Comment by regosen** [comment]
Should be fixed now with last merge
