### ISSUE TITLE
Any help please

### ISSUE THREAD

**Issue by MudarSoftware** [regosen/gallery_get#82]
Traceback (most recent call last):
  File "d:/Programming/Python/gallery_get/gallery_get.py", line 444, in run
    page = data.read().decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 69190: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:/Programming/Python/gallery_get/gallery_get.py", line 468, in run_wrapped
    root = GalleryGet(myurl, dest or DEST_ROOT, titleAsFolder, allowGenericPlugin).run()
  File "d:/Programming/Python/gallery_get/gallery_get.py", line 454, in run
    print("Skipping inaccessible link (%d): %s" % (error.code, self.url))
AttributeError: 'UnicodeDecodeError' object has no attribute 'code'
Using params:

**Comment by regosen** [comment]
Hi @MudarSoftware, I just pushed a new version of the script (1.8.17) that fixes several issues, and I believe it will help you as well.

Please update at your convenience and try again!

**Comment by regosen** [comment]
Closing this issue after seeing the thumbs up, please re-open if it still doesn't work!
