### ISSUE TITLE
imagefap broken

### ISSUE THREAD

**Issue by youngdarwin** [regosen/gallery_get#83]
All downloads from imagefap.com seem to have broken. I just grabbed the latest code and I get the same results:

```
Traceback (most recent call last):
  File "gallery_get.py", line 466, in run_wrapped
    root = GalleryGet(myurl, dest or DEST_ROOT, titleAsFolder, allowGenericPlugin).run()
  File "gallery_get.py", line 457, in run
    return self.queue_jobs(page, root, subtitle)
  File "gallery_get.py", line 384, in queue_jobs
    links = run_match(self.plugin.redirect, page)
  File "gallery_get.py", line 118, in run_match
    result = match(source)
  File "/home/youngd/projects/pron/gallery_get-master-2021-02-27/gallery_plugins/plugin_imagefap.py", line 27, in redirect
    indexed_source = urlopen_text(indexed_page)
  File "/home/youngd/projects/pron/gallery_get-master-2021-02-27/gallery_utils.py", line 75, in urlopen_text
    data = urlopen_safe(url)
  File "/home/youngd/projects/pron/gallery_get-master-2021-02-27/gallery_utils.py", line 27, in urlopen_safe
    return urlopen(q)
  File "/usr/lib64/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.4/urllib/request.py", line 470, in open
    response = meth(req, response)
  File "/usr/lib64/python3.4/urllib/request.py", line 580, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.4/urllib/request.py", line 508, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 588, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 308: Permanent Redirect
Using params: ['https://www.imagefap.com/pictures/9317363/Marcela-Iglesias', './images', False]
```

**Comment by regosen** [comment]
Thanks for reporting.  I just updated this script with a fix to handle these types of redirects, can you try again with latest version (1.8.18)?

**Comment by youngdarwin** [comment]
This seems to work fine. Thanks! I'll close the ticket.
